# File: home-services-marketplace/k8s/rabbitmq-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: home-services
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    name: amqp
    targetPort: 5672
  - port: 15672
    name: management
    targetPort: 15672
  - port: 15692
    name: prometheus
    targetPort: 15692
  selector:
    app: rabbitmq
