# devops/kubernetes/config/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
type: Opaque
data:
    jwt-secret: eW91cl9qd3Rfc2VjcmV0 # base64 encoded "your_jwt_secret"
    mercadopago-token: eW91cl9tZXJjYWRvcGFnb19hY2Nlc3NfdG9rZW4= # base64 encoded "your_mercadopago_access_token"
