# devops/kubernetes/deployments/user-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-service
spec:
    replicas: 2
    selector:
        matchLabels:
            app: user-service
    template:
        metadata:
            labels:
                app: user-service
        spec:
            containers:
                -
                    name: user-service
                    image: home-services/user-service:latest
                    ports:
                        -
                            containerPort: 3001
                    env:
                        -
                            name: MONGODB_URI
                            value: "mongodb://mongodb:27017/user-service"
                        -
                            name: JWT_SECRET
                            valueFrom:
                                secretKeyRef:
                                    name: app-secrets
                                    key: jwt-secret
